wd=800
hg=400
binck1 = ['EUTELSAT','NEXITY','VALEO','ACCOR','AIR FRANCE','CHRISTIAN DIOR','ERAMET','LVMH','UBISOFT']
cand1 = ['IPSOS', 'WENDEL', 'SCHNEIDER', 'VEOLIA', 'STMICROELECTRONICS', 'VALEO', 'RENAULT', 'LEGRAND', 'ARKEMA', 'RHODIA']
cand2 = ['CARBONE LORRAINE', 'DERICHEBOURG', 'TRIGANO', 'BIC', 'SEB', 'INGENICO', 'ZODIAC', 'PUBLICIS', 'REXEL', 'BUREAU VERITAS']
cand3 = ['RHODIA', 'CARBONE LORRAINE', 'DERICHEBOURG', 'BIC', 'ZODIAC', 'PUBLICIS']

binck = ['ACCOR', 'AIR FRANCE', 'CARREFOUR', 'ERAMET', 'LVMH', 'SCHNEIDER', 'UBISOFT', 'WENDEL']
cand = ['IPSOS', 'VEOLIA', 'STMICROELECTRONICS', 'VALEO', 'RENAULT', 'LEGRAND', 'ARKEMA', 'RHODIA', 'CARBONE LORRAINE', 'DERICHEBOURG', 'BIC', 'ZODIAC', 'PUBLICIS', 'FAURECIA', 'BUREAU VERITAS']
candsrd = ['SAFRAN', 'NRJ GROUP', 'CASINO', 'ALTRAN', 'ICADE', 'SOPRA', 'SOITEC', 'CGG VERITAS', 'VALLOUREC', 'KAUFMAN', 'SODEXO', 'GECINA']
candsrd2a = ['APRIL', 'AUDIKA', 'EDENRED', 'FAIVELEY', 'FONCIERE DES MURS', 'LISI', 'THERMADOR', 'TOUR EIFFEL']
candsrd2 = ['FR0004037125', 'FR0000063752', 'FR0010908533', 'FR0000053142', 'FR0000060303', 'FR0000050353', 'FR0000061111', 'FR0000036816']

cand4 = ['EUROFINS', 'SOPRA', 'ALTEN', 'KAUFMAN', 'ESSILOR', 'SAINT', 'INGENICO', 'CASINO']

srd1=[x[1] for x in srd]
